// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero/index.svelte';
import ScalingElement from './ScalingElement/index.svelte';

export const components = {
	hero: Hero,
	hero_with_media: ScalingElement
};
